version: '3'
services:
    web:
        image: hrjakobsen/laml:latest
        volumes:
            - ./cgi-bin:/usr/local/cgi-bin
            - ./static:/var/www/html
            - laml-data:/data
        ports:
            - "4000:80"
        environment:
          - LAMLDIR=/usr/bin/laml/
volumes:
    laml-data:
